/**
 * Mapa de modelos populares no Brasil por marca.
 * Inclui smartphones, notebooks, tablets e outros dispositivos.
 * Atualizado com os modelos mais vendidos/reparados no mercado brasileiro.
 */
export const BRAND_MODELS: Record<string, string[]> = {
  // ── APPLE ──────────────────────────────────────────────────────────────────
  Apple: [
    // iPhone
    "iPhone 16 Pro Max",
    "iPhone 16 Pro",
    "iPhone 16 Plus",
    "iPhone 16",
    "iPhone 15 Pro Max",
    "iPhone 15 Pro",
    "iPhone 15 Plus",
    "iPhone 15",
    "iPhone 14 Pro Max",
    "iPhone 14 Pro",
    "iPhone 14 Plus",
    "iPhone 14",
    "iPhone 13 Pro Max",
    "iPhone 13 Pro",
    "iPhone 13",
    "iPhone 13 Mini",
    "iPhone 12 Pro Max",
    "iPhone 12 Pro",
    "iPhone 12",
    "iPhone 12 Mini",
    "iPhone 11 Pro Max",
    "iPhone 11 Pro",
    "iPhone 11",
    "iPhone XS Max",
    "iPhone XS",
    "iPhone XR",
    "iPhone X",
    "iPhone SE (3ª geração)",
    "iPhone SE (2ª geração)",
    "iPhone 8 Plus",
    "iPhone 8",
    "iPhone 7 Plus",
    "iPhone 7",
    "iPhone 6S Plus",
    "iPhone 6S",
    "iPhone 6 Plus",
    "iPhone 6",
    // iPad
    "iPad Pro 13\" (M4)",
    "iPad Pro 11\" (M4)",
    "iPad Air 13\" (M2)",
    "iPad Air 11\" (M2)",
    "iPad (10ª geração)",
    "iPad (9ª geração)",
    "iPad Mini (6ª geração)",
    // MacBook
    "MacBook Pro 16\" (M3 Max)",
    "MacBook Pro 14\" (M3 Pro)",
    "MacBook Pro 13\" (M2)",
    "MacBook Air 15\" (M3)",
    "MacBook Air 13\" (M3)",
    "MacBook Air 13\" (M2)",
    // Apple Watch
    "Apple Watch Series 10",
    "Apple Watch Series 9",
    "Apple Watch Ultra 2",
    "Apple Watch SE (2ª geração)",
    // AirPods
    "AirPods Pro (2ª geração)",
    "AirPods (3ª geração)",
    "AirPods Max",
  ],

  // ── SAMSUNG ────────────────────────────────────────────────────────────────
  Samsung: [
    // Galaxy S (flagship)
    "Galaxy S25 Ultra",
    "Galaxy S25+",
    "Galaxy S25",
    "Galaxy S24 Ultra",
    "Galaxy S24+",
    "Galaxy S24",
    "Galaxy S23 Ultra",
    "Galaxy S23+",
    "Galaxy S23",
    "Galaxy S22 Ultra",
    "Galaxy S22+",
    "Galaxy S22",
    "Galaxy S21 Ultra",
    "Galaxy S21+",
    "Galaxy S21",
    "Galaxy S21 FE",
    "Galaxy S20 Ultra",
    "Galaxy S20+",
    "Galaxy S20",
    "Galaxy S20 FE",
    "Galaxy S10+",
    "Galaxy S10",
    "Galaxy S10e",
    "Galaxy S10 Lite",
    "Galaxy S9+",
    "Galaxy S9",
    "Galaxy S8+",
    "Galaxy S8",
    // Galaxy A (intermediário)
    "Galaxy A56",
    "Galaxy A55",
    "Galaxy A54",
    "Galaxy A53",
    "Galaxy A52s",
    "Galaxy A52",
    "Galaxy A51",
    "Galaxy A36",
    "Galaxy A35",
    "Galaxy A34",
    "Galaxy A33",
    "Galaxy A32",
    "Galaxy A25",
    "Galaxy A24",
    "Galaxy A23",
    "Galaxy A22",
    "Galaxy A16",
    "Galaxy A15",
    "Galaxy A14",
    "Galaxy A13",
    "Galaxy A12",
    "Galaxy A05s",
    "Galaxy A05",
    "Galaxy A04s",
    "Galaxy A04",
    "Galaxy A03s",
    "Galaxy A03",
    // Galaxy M (entrada)
    "Galaxy M55",
    "Galaxy M35",
    "Galaxy M15",
    "Galaxy M14",
    "Galaxy M13",
    // Galaxy Z (dobráveis)
    "Galaxy Z Fold 6",
    "Galaxy Z Fold 5",
    "Galaxy Z Fold 4",
    "Galaxy Z Flip 6",
    "Galaxy Z Flip 5",
    "Galaxy Z Flip 4",
    "Galaxy Z Flip 3",
    // Galaxy Tab
    "Galaxy Tab S9 Ultra",
    "Galaxy Tab S9+",
    "Galaxy Tab S9",
    "Galaxy Tab S9 FE",
    "Galaxy Tab S8 Ultra",
    "Galaxy Tab S8+",
    "Galaxy Tab S8",
    "Galaxy Tab A9+",
    "Galaxy Tab A9",
    "Galaxy Tab A8",
    "Galaxy Tab A7 Lite",
    // Galaxy Watch
    "Galaxy Watch 7",
    "Galaxy Watch Ultra",
    "Galaxy Watch 6 Classic",
    "Galaxy Watch 6",
    "Galaxy Watch 5 Pro",
    "Galaxy Watch 5",
    "Galaxy Watch 4 Classic",
    "Galaxy Watch 4",
    // Galaxy Buds
    "Galaxy Buds3 Pro",
    "Galaxy Buds3",
    "Galaxy Buds2 Pro",
    "Galaxy Buds2",
    "Galaxy Buds Live",
    "Galaxy Buds+",
  ],

  // ── MOTOROLA ───────────────────────────────────────────────────────────────
  Motorola: [
    // Edge
    "Edge 50 Ultra",
    "Edge 50 Pro",
    "Edge 50 Fusion",
    "Edge 50 Neo",
    "Edge 40 Pro",
    "Edge 40",
    "Edge 40 Neo",
    "Edge 30 Ultra",
    "Edge 30 Pro",
    "Edge 30 Fusion",
    "Edge 30 Neo",
    "Edge 30",
    "Edge 20 Pro",
    "Edge 20",
    "Edge 20 Lite",
    // Moto G (mais vendidos no Brasil)
    "Moto G85",
    "Moto G75",
    "Moto G55",
    "Moto G45",
    "Moto G35",
    "Moto G25",
    "Moto G15",
    "Moto G84",
    "Moto G73",
    "Moto G72",
    "Moto G62",
    "Moto G52",
    "Moto G42",
    "Moto G32",
    "Moto G22",
    "Moto G13",
    "Moto G14",
    "Moto G04",
    "Moto G04s",
    "Moto G200",
    "Moto G100",
    "Moto G71",
    "Moto G60",
    "Moto G50",
    "Moto G40 Fusion",
    "Moto G30",
    "Moto G20",
    "Moto G10",
    "Moto G9 Power",
    "Moto G9 Play",
    "Moto G9 Plus",
    "Moto G8 Power",
    "Moto G8 Play",
    "Moto G8 Plus",
    "Moto G7 Power",
    "Moto G7 Play",
    "Moto G7 Plus",
    "Moto G7",
    "Moto G6 Play",
    "Moto G6 Plus",
    "Moto G6",
    "Moto G5S Plus",
    "Moto G5S",
    "Moto G5 Plus",
    "Moto G5",
    // Moto E
    "Moto E22",
    "Moto E22i",
    "Moto E20",
    "Moto E13",
    "Moto E7 Plus",
    "Moto E7 Power",
    "Moto E6s",
    "Moto E6 Plus",
    // Razr
    "Razr 50 Ultra",
    "Razr 50",
    "Razr 40 Ultra",
    "Razr 40",
    // Moto Z
    "Moto Z4",
    "Moto Z3 Play",
    "Moto Z2 Play",
  ],

  // ── XIAOMI ─────────────────────────────────────────────────────────────────
  Xiaomi: [
    // Xiaomi 14
    "Xiaomi 14 Ultra",
    "Xiaomi 14 Pro",
    "Xiaomi 14",
    "Xiaomi 14T Pro",
    "Xiaomi 14T",
    // Xiaomi 13
    "Xiaomi 13 Ultra",
    "Xiaomi 13 Pro",
    "Xiaomi 13",
    "Xiaomi 13T Pro",
    "Xiaomi 13T",
    "Xiaomi 13 Lite",
    // Xiaomi 12
    "Xiaomi 12 Pro",
    "Xiaomi 12",
    "Xiaomi 12 Lite",
    "Xiaomi 12X",
    // Redmi Note
    "Redmi Note 14 Pro+",
    "Redmi Note 14 Pro",
    "Redmi Note 14",
    "Redmi Note 13 Pro+",
    "Redmi Note 13 Pro",
    "Redmi Note 13",
    "Redmi Note 13R",
    "Redmi Note 12 Pro+",
    "Redmi Note 12 Pro",
    "Redmi Note 12",
    "Redmi Note 12S",
    "Redmi Note 11 Pro+",
    "Redmi Note 11 Pro",
    "Redmi Note 11",
    "Redmi Note 11S",
    "Redmi Note 10 Pro",
    "Redmi Note 10",
    "Redmi Note 10S",
    "Redmi Note 9 Pro",
    "Redmi Note 9",
    "Redmi Note 9S",
    "Redmi Note 8 Pro",
    "Redmi Note 8",
    "Redmi Note 7",
    // Redmi
    "Redmi 14C",
    "Redmi 13C",
    "Redmi 13",
    "Redmi 12C",
    "Redmi 12",
    "Redmi 10C",
    "Redmi 10",
    "Redmi 9C",
    "Redmi 9A",
    "Redmi 9",
    // POCO
    "POCO X6 Pro",
    "POCO X6",
    "POCO X5 Pro",
    "POCO X5",
    "POCO X4 Pro",
    "POCO X4 GT",
    "POCO X3 Pro",
    "POCO X3 NFC",
    "POCO M6 Pro",
    "POCO M5s",
    "POCO M5",
    "POCO M4 Pro",
    "POCO F5 Pro",
    "POCO F5",
    "POCO F4 GT",
    "POCO F4",
    // Mi
    "Mi 11 Ultra",
    "Mi 11 Pro",
    "Mi 11",
    "Mi 11 Lite",
    "Mi 10T Pro",
    "Mi 10T",
    "Mi 10 Pro",
    "Mi 10",
    "Mi 9T Pro",
    "Mi 9T",
    "Mi 9",
    "Mi 8",
    // Tablet
    "Xiaomi Pad 6 Pro",
    "Xiaomi Pad 6",
    "Xiaomi Pad 5",
  ],

  // ── LG ─────────────────────────────────────────────────────────────────────
  LG: [
    "LG Velvet",
    "LG Wing",
    "LG K62",
    "LG K52",
    "LG K42",
    "LG K22",
    "LG K12 Plus",
    "LG K11",
    "LG K10 (2018)",
    "LG K9",
    "LG Q60",
    "LG Q6",
    "LG Q7",
    "LG G8 ThinQ",
    "LG G7 ThinQ",
    "LG G6",
    "LG G5",
    "LG G4",
    "LG G3",
    "LG V60 ThinQ",
    "LG V50 ThinQ",
    "LG V40 ThinQ",
    "LG V30",
    "LG Stylo 6",
    "LG Stylo 5",
    "LG X Power",
    "LG X Screen",
    "LG Nexus 5X",
  ],

  // ── NOKIA ──────────────────────────────────────────────────────────────────
  Nokia: [
    "Nokia G42",
    "Nokia G22",
    "Nokia G21",
    "Nokia G20",
    "Nokia G11",
    "Nokia G10",
    "Nokia C32",
    "Nokia C22",
    "Nokia C21 Plus",
    "Nokia C21",
    "Nokia C12",
    "Nokia C02",
    "Nokia X30",
    "Nokia X20",
    "Nokia X10",
    "Nokia 5.4",
    "Nokia 5.3",
    "Nokia 3.4",
    "Nokia 3.2",
    "Nokia 2.4",
    "Nokia 2.3",
    "Nokia 1.4",
    "Nokia 8.3 5G",
    "Nokia 7.2",
    "Nokia 6.2",
    "Nokia 105 (2023)",
    "Nokia 110 4G",
    "Nokia 150",
    "Nokia 3310",
  ],

  // ── SONY ───────────────────────────────────────────────────────────────────
  Sony: [
    "Xperia 1 VI",
    "Xperia 5 VI",
    "Xperia 10 VI",
    "Xperia 1 V",
    "Xperia 5 V",
    "Xperia 10 V",
    "Xperia 1 IV",
    "Xperia 5 IV",
    "Xperia 10 IV",
    "Xperia 1 III",
    "Xperia 5 III",
    "Xperia 10 III",
    "Xperia 1 II",
    "Xperia 5 II",
    "Xperia 10 II",
    "Xperia L4",
    "Xperia L3",
    "Xperia L2",
    "Xperia XA2 Ultra",
    "Xperia XA2",
    "Xperia XZ3",
    "Xperia XZ2",
    "Xperia XZ1",
    "Xperia XZ",
    "Xperia Z5",
    "Xperia Z3",
  ],

  // ── HUAWEI ─────────────────────────────────────────────────────────────────
  Huawei: [
    "P60 Pro",
    "P50 Pro",
    "P50",
    "P40 Pro+",
    "P40 Pro",
    "P40",
    "P40 Lite",
    "P30 Pro",
    "P30",
    "P30 Lite",
    "P20 Pro",
    "P20",
    "P20 Lite",
    "Mate 60 Pro",
    "Mate 50 Pro",
    "Mate 40 Pro",
    "Mate 30 Pro",
    "Mate 20 Pro",
    "Mate 20",
    "Mate 20 Lite",
    "Mate 10 Pro",
    "Nova 11 Pro",
    "Nova 11",
    "Nova 9 Pro",
    "Nova 9",
    "Nova 8 Pro",
    "Nova 8",
    "Nova 7i",
    "Nova 5T",
    "Nova 3i",
    "Y9 Prime (2019)",
    "Y9 (2019)",
    "Y7 Pro (2019)",
    "Y6 Pro",
    "Y5 Lite",
    "MediaPad T5",
    "MatePad Pro",
    "MatePad 11",
    "MatePad T10s",
  ],

  // ── POSITIVO ───────────────────────────────────────────────────────────────
  Positivo: [
    "Twist 6 Pro",
    "Twist 6",
    "Twist 5G",
    "Twist 4 Pro",
    "Twist 4",
    "Twist 3 Pro",
    "Twist 3",
    "Twist 2 Pro",
    "Twist 2",
    "Twist",
    "Q20",
    "Q10",
    "S560",
    "S540",
    "S520",
    "S510",
    "S415",
    "S413",
    "S406",
    "S405",
    "S404",
    "S403",
    "Motion Plus",
    "Motion",
    "Bono",
    "Bono 4G",
    "Positivo Duo",
    // Notebooks
    "Motion C4128E",
    "Motion C4500H",
    "Motion Gray C4128E",
    "Duo C464B",
    "Union i5",
    "Master N7140",
    "Master N6140",
    "Stilo One",
    "Stilo XC3",
    "Stilo XC5",
    "Stilo XC7",
    "Stilo XC8",
    "Stilo XC9",
    "Stilo XC10",
    "Stilo XC11",
    "Stilo XC12",
    "Stilo XC13",
    "Stilo XC14",
    "Stilo XC15",
  ],

  // ── MULTILASER ─────────────────────────────────────────────────────────────
  Multilaser: [
    "F Pro 2",
    "F Pro",
    "F",
    "G Max",
    "G Pro",
    "G",
    "M Pro",
    "M",
    "E Lite 3",
    "E Lite 2",
    "E Lite",
    "E Pro",
    "E",
    "Zapp",
    "Zapp 3G",
    "Zapp 4G",
    "Vita 3",
    "Vita 2",
    "Vita",
    "Selfie Pro",
    "Selfie",
    "Tablet M7",
    "Tablet M8",
    "Tablet M9",
    "Tablet M10",
    "Tablet M10A",
    "Tablet M7S Go",
    "Tablet M8 3G",
    "Tablet M10 4G",
    "Notebook Legacy",
    "Notebook Legacy Book",
    "Notebook Legacy Cloud",
    "Notebook Legacy Air",
    "Notebook Legacy Ultra",
  ],

  // ── ASUS ───────────────────────────────────────────────────────────────────
  Asus: [
    // Smartphones
    "Zenfone 11 Ultra",
    "Zenfone 10",
    "Zenfone 9",
    "Zenfone 8",
    "Zenfone 7 Pro",
    "Zenfone 7",
    "Zenfone 6",
    "Zenfone 5Z",
    "Zenfone 5",
    "Zenfone Max Pro M2",
    "Zenfone Max Pro M1",
    "Zenfone Max M2",
    "Zenfone Max M1",
    "ROG Phone 8 Pro",
    "ROG Phone 8",
    "ROG Phone 7 Ultimate",
    "ROG Phone 7",
    "ROG Phone 6 Pro",
    "ROG Phone 6",
    "ROG Phone 5s Pro",
    "ROG Phone 5s",
    "ROG Phone 5 Pro",
    "ROG Phone 5",
    // Notebooks
    "VivoBook 15",
    "VivoBook 14",
    "VivoBook 16X",
    "VivoBook S15",
    "VivoBook S14",
    "VivoBook Pro 15",
    "VivoBook Pro 14",
    "ZenBook 14",
    "ZenBook 15",
    "ZenBook Pro Duo 15",
    "ZenBook S 13 OLED",
    "ExpertBook B9",
    "ExpertBook B5",
    "ROG Zephyrus G14",
    "ROG Zephyrus G15",
    "ROG Strix G15",
    "ROG Strix G16",
    "ROG Strix Scar 15",
    "ROG Strix Scar 16",
    "TUF Gaming A15",
    "TUF Gaming A17",
    "TUF Gaming F15",
    "TUF Gaming F17",
    // Tablets
    "ZenPad 10",
    "ZenPad 8",
    "ROG Flow Z13",
  ],

  // ── DELL ───────────────────────────────────────────────────────────────────
  Dell: [
    "Inspiron 15 3000",
    "Inspiron 15 5000",
    "Inspiron 15 7000",
    "Inspiron 14 5000",
    "Inspiron 14 7000",
    "Inspiron 13 5000",
    "Inspiron 13 7000",
    "Inspiron 16 5000",
    "Inspiron 16 7000",
    "Vostro 15 3000",
    "Vostro 15 5000",
    "Vostro 14 3000",
    "Vostro 14 5000",
    "XPS 13",
    "XPS 13 Plus",
    "XPS 15",
    "XPS 17",
    "Latitude 5420",
    "Latitude 5520",
    "Latitude 7420",
    "Latitude 7520",
    "Latitude 3420",
    "Latitude 3520",
    "Precision 5570",
    "Precision 7670",
    "G15",
    "G16",
    "Alienware m15 R7",
    "Alienware m16",
    "Alienware x14",
    "Alienware x15",
    "Alienware x17",
  ],

  // ── HP ─────────────────────────────────────────────────────────────────────
  HP: [
    "Pavilion 15",
    "Pavilion 14",
    "Pavilion x360 15",
    "Pavilion x360 14",
    "Pavilion Aero 13",
    "Envy 15",
    "Envy 14",
    "Envy x360 15",
    "Envy x360 13",
    "Spectre x360 14",
    "Spectre x360 16",
    "EliteBook 840 G9",
    "EliteBook 850 G9",
    "EliteBook 1040 G9",
    "ProBook 445 G9",
    "ProBook 450 G9",
    "ProBook 455 G9",
    "Omen 15",
    "Omen 16",
    "Omen 17",
    "Victus 15",
    "Victus 16",
    "Stream 11",
    "Chromebook 11",
    "Chromebook 14",
    "ZBook Studio G9",
    "ZBook Fury G9",
    // Impressoras
    "DeskJet 2776",
    "DeskJet 3776",
    "DeskJet 4176",
    "Smart Tank 516",
    "Smart Tank 615",
    "Smart Tank 720",
    "OfficeJet Pro 9020",
    "OfficeJet Pro 8020",
    "LaserJet Pro M15w",
    "LaserJet Pro M28w",
    "LaserJet Pro MFP M130fw",
    "LaserJet Pro MFP M227fdw",
  ],

  // ── LENOVO ─────────────────────────────────────────────────────────────────
  Lenovo: [
    // Notebooks
    "IdeaPad 3i",
    "IdeaPad 3",
    "IdeaPad 5i",
    "IdeaPad 5",
    "IdeaPad 5 Pro",
    "IdeaPad Gaming 3i",
    "IdeaPad Gaming 3",
    "IdeaPad Flex 5i",
    "IdeaPad Flex 5",
    "IdeaPad Slim 3i",
    "IdeaPad Slim 5i",
    "IdeaPad Slim 5",
    "ThinkPad E14",
    "ThinkPad E15",
    "ThinkPad L14",
    "ThinkPad L15",
    "ThinkPad T14",
    "ThinkPad T14s",
    "ThinkPad T15",
    "ThinkPad X1 Carbon",
    "ThinkPad X1 Extreme",
    "ThinkPad X1 Yoga",
    "ThinkPad X13",
    "ThinkPad P14s",
    "ThinkPad P15s",
    "Legion 5i",
    "Legion 5",
    "Legion 5 Pro",
    "Legion 7i",
    "Legion 7",
    "Legion Slim 5i",
    "Legion Slim 5",
    "Yoga 6",
    "Yoga 7i",
    "Yoga 9i",
    "Yoga Slim 7i",
    "Yoga Slim 7",
    "Yoga Slim 6i",
    "Chromebook Flex 5i",
    // Tablets
    "Tab P11 Pro Gen 2",
    "Tab P11 Gen 2",
    "Tab P11",
    "Tab M10 Plus Gen 3",
    "Tab M10 Plus",
    "Tab M10 FHD Plus",
    "Tab M8 Gen 3",
    "Tab M8",
    "Tab P12 Pro",
    // Smartphones
    "Moto G (Lenovo)",
    "K12 Pro",
    "K13 Note",
  ],

  // ── ACER ───────────────────────────────────────────────────────────────────
  Acer: [
    "Aspire 3",
    "Aspire 5",
    "Aspire 7",
    "Aspire Vero",
    "Aspire Lite",
    "Swift 3",
    "Swift 5",
    "Swift X",
    "Swift Go 14",
    "Swift Go 16",
    "Spin 3",
    "Spin 5",
    "Nitro 5",
    "Nitro 7",
    "Nitro V 15",
    "Predator Helios 300",
    "Predator Helios 16",
    "Predator Helios 18",
    "Predator Triton 300",
    "Predator Triton 500",
    "TravelMate P2",
    "TravelMate P4",
    "Chromebook 314",
    "Chromebook 315",
    "Chromebook Spin 514",
    "ConceptD 3",
    "ConceptD 5",
  ],

  // ── MICROSOFT ──────────────────────────────────────────────────────────────
  Microsoft: [
    "Surface Pro 10",
    "Surface Pro 9",
    "Surface Pro 8",
    "Surface Pro 7+",
    "Surface Pro 7",
    "Surface Pro X",
    "Surface Laptop 6",
    "Surface Laptop 5",
    "Surface Laptop 4",
    "Surface Laptop 3",
    "Surface Laptop Go 3",
    "Surface Laptop Go 2",
    "Surface Laptop Go",
    "Surface Laptop Studio 2",
    "Surface Laptop Studio",
    "Surface Book 3",
    "Surface Go 4",
    "Surface Go 3",
    "Surface Go 2",
    "Surface Duo 2",
    "Surface Duo",
    "Xbox Series X",
    "Xbox Series S",
    "Xbox One X",
    "Xbox One S",
    "Xbox One",
    "Xbox 360",
  ],

  // ── GOOGLE ─────────────────────────────────────────────────────────────────
  Google: [
    "Pixel 9 Pro XL",
    "Pixel 9 Pro",
    "Pixel 9 Pro Fold",
    "Pixel 9",
    "Pixel 8 Pro",
    "Pixel 8",
    "Pixel 8a",
    "Pixel 7 Pro",
    "Pixel 7",
    "Pixel 7a",
    "Pixel 6 Pro",
    "Pixel 6",
    "Pixel 6a",
    "Pixel 5",
    "Pixel 4a",
    "Pixel 4 XL",
    "Pixel 4",
    "Pixel 3a XL",
    "Pixel 3a",
    "Pixel 3 XL",
    "Pixel 3",
    "Pixel 2 XL",
    "Pixel 2",
    "Pixel XL",
    "Pixel",
    "Pixel Tablet",
    "Pixel Fold",
    "Nest Hub Max",
    "Nest Hub (2ª geração)",
    "Nest Mini",
  ],

  // ── REALME ─────────────────────────────────────────────────────────────────
  Realme: [
    "GT 6 Pro",
    "GT 6",
    "GT 5 Pro",
    "GT 5",
    "GT Neo 6",
    "GT Neo 5",
    "GT Neo 3",
    "GT Neo 2",
    "GT Master Edition",
    "GT",
    "12 Pro+",
    "12 Pro",
    "12",
    "12+",
    "11 Pro+",
    "11 Pro",
    "11",
    "10 Pro+",
    "10 Pro",
    "10",
    "9 Pro+",
    "9 Pro",
    "9",
    "9i",
    "8 Pro",
    "8",
    "8i",
    "7 Pro",
    "7",
    "7i",
    "6 Pro",
    "6",
    "6i",
    "5 Pro",
    "5",
    "5i",
    "C55",
    "C53",
    "C51",
    "C35",
    "C33",
    "C31",
    "C30",
    "C25Y",
    "C25s",
    "C21Y",
    "C21",
    "C20",
    "C15",
    "C12",
    "C11",
    "Narzo 60 Pro",
    "Narzo 60",
    "Narzo 50 Pro",
    "Narzo 50",
    "Narzo 50A Prime",
    "Narzo 50A",
    "Narzo 50i",
    "Narzo 30 Pro",
    "Narzo 30",
    "Narzo 20 Pro",
    "Narzo 20",
  ],

  // ── OPPO ───────────────────────────────────────────────────────────────────
  Oppo: [
    "Find X7 Ultra",
    "Find X7 Pro",
    "Find X7",
    "Find X6 Pro",
    "Find X6",
    "Find X5 Pro",
    "Find X5",
    "Find X3 Pro",
    "Find X3",
    "Find X2 Pro",
    "Find X2",
    "Reno 12 Pro",
    "Reno 12",
    "Reno 11 Pro",
    "Reno 11",
    "Reno 10 Pro+",
    "Reno 10 Pro",
    "Reno 10",
    "Reno 8 Pro",
    "Reno 8",
    "Reno 8T",
    "Reno 7 Pro",
    "Reno 7",
    "Reno 6 Pro",
    "Reno 6",
    "A98",
    "A78",
    "A58",
    "A38",
    "A18",
    "A17",
    "A16",
    "A15s",
    "A15",
    "A54s",
    "A54",
    "A53s",
    "A53",
    "A52",
    "A12",
    "A9 (2020)",
    "A5 (2020)",
  ],

  // ── VIVO ───────────────────────────────────────────────────────────────────
  Vivo: [
    "X100 Ultra",
    "X100 Pro",
    "X100",
    "X90 Pro",
    "X90",
    "X80 Pro",
    "X80",
    "X70 Pro+",
    "X70 Pro",
    "X70",
    "X60 Pro+",
    "X60 Pro",
    "X60",
    "V30 Pro",
    "V30",
    "V29 Pro",
    "V29",
    "V27 Pro",
    "V27",
    "V25 Pro",
    "V25",
    "V23 Pro",
    "V23",
    "V21",
    "V20 Pro",
    "V20",
    "Y200 Pro",
    "Y200",
    "Y100",
    "Y78",
    "Y56",
    "Y36",
    "Y27s",
    "Y27",
    "Y22s",
    "Y22",
    "Y21s",
    "Y21",
    "Y20s",
    "Y20",
    "Y15s",
    "Y15",
    "Y12s",
    "Y12",
    "Y11",
    "Y02s",
    "Y02",
    "T2 Pro",
    "T2",
    "T1 Pro",
    "T1",
    "iQOO 12 Pro",
    "iQOO 12",
    "iQOO 11 Pro",
    "iQOO 11",
    "iQOO Neo 9 Pro",
    "iQOO Neo 9",
    "iQOO Z9 Turbo",
    "iQOO Z9",
    "iQOO Z7 Pro",
    "iQOO Z7",
  ],

  // ── ONEPLUS ────────────────────────────────────────────────────────────────
  OnePlus: [
    "12 Pro",
    "12",
    "11 Pro",
    "11",
    "10 Pro",
    "10T",
    "10",
    "9 Pro",
    "9",
    "9R",
    "8T",
    "8 Pro",
    "8",
    "7T Pro",
    "7T",
    "7 Pro",
    "7",
    "6T",
    "6",
    "Nord 4",
    "Nord 3",
    "Nord 2T",
    "Nord 2",
    "Nord CE 3 Lite",
    "Nord CE 3",
    "Nord CE 2 Lite",
    "Nord CE 2",
    "Nord CE",
    "Nord N30",
    "Nord N20",
    "Nord N10",
    "Open",
    "Pad 2",
    "Pad",
  ],

  // ── TCL ────────────────────────────────────────────────────────────────────
  TCL: [
    "50 Pro",
    "50",
    "50 XE NxtPaper",
    "50 SE",
    "40 NxtPaper",
    "40 SE",
    "40 R",
    "40 C",
    "30 SE",
    "30+",
    "30",
    "20 Pro 5G",
    "20S",
    "20L+",
    "20L",
    "20Y",
    "20E",
    "10 Pro",
    "10L",
    "10 SE",
    "Tab 10 Gen 2",
    "Tab 10 HD",
    "Tab 8 LE",
    "NxtPaper 11",
    "NxtPaper 10s",
  ],

  // ── ALCATEL ────────────────────────────────────────────────────────────────
  Alcatel: [
    "3X (2020)",
    "3L (2021)",
    "1S (2021)",
    "1V (2021)",
    "1B (2020)",
    "1A (2021)",
    "1SE",
    "1L",
    "3",
    "3T",
    "5V",
    "7",
    "Pixi 4",
    "Pop 4",
    "Idol 5",
    "Flash",
    "Go Flip",
    "Smartflip",
  ],

  // ── ZTE ────────────────────────────────────────────────────────────────────
  ZTE: [
    "Blade V50 Design",
    "Blade V50 Vita",
    "Blade V40 Design",
    "Blade V40 Vita",
    "Blade V40 Pro",
    "Blade A72",
    "Blade A52",
    "Blade A32",
    "Axon 40 Ultra",
    "Axon 40 Pro",
    "Axon 30 Ultra",
    "Axon 30 Pro",
    "Axon 20",
    "Nubia Z50 Ultra",
    "Nubia Z50S Pro",
    "Nubia Red Magic 9 Pro",
    "Nubia Red Magic 8 Pro",
    "Nubia Red Magic 7 Pro",
    "Nubia Red Magic 7",
  ],

  // ── INFINIX ────────────────────────────────────────────────────────────────
  Infinix: [
    "Zero 40 Pro",
    "Zero 40",
    "Zero 30 Pro",
    "Zero 30",
    "Zero 20",
    "Note 40 Pro",
    "Note 40",
    "Note 30 Pro",
    "Note 30",
    "Note 12 Pro",
    "Note 12",
    "Hot 40 Pro",
    "Hot 40",
    "Hot 30 Play",
    "Hot 30",
    "Hot 20 Play",
    "Hot 20",
    "Smart 8 Pro",
    "Smart 8",
    "Smart 7",
    "GT 20 Pro",
    "GT 10 Pro",
  ],

  // ── TECNO ──────────────────────────────────────────────────────────────────
  Tecno: [
    "Phantom X2 Pro",
    "Phantom X2",
    "Phantom V Fold",
    "Camon 30 Pro",
    "Camon 30",
    "Camon 20 Pro",
    "Camon 20",
    "Spark 20 Pro",
    "Spark 20",
    "Spark 10 Pro",
    "Spark 10",
    "Pop 7 Pro",
    "Pop 7",
    "Pova 6 Pro",
    "Pova 6",
    "Pova 5 Pro",
    "Pova 5",
  ],

  // ── AMAZON ─────────────────────────────────────────────────────────────────
  Amazon: [
    "Fire HD 10 (2023)",
    "Fire HD 10 Plus",
    "Fire HD 8 (2022)",
    "Fire HD 8 Plus",
    "Fire 7 (2022)",
    "Fire HD 10 Kids",
    "Fire HD 8 Kids",
    "Kindle Paperwhite (11ª geração)",
    "Kindle Paperwhite Signature Edition",
    "Kindle (11ª geração)",
    "Kindle Oasis",
    "Echo Dot (5ª geração)",
    "Echo (4ª geração)",
    "Echo Show 8",
    "Echo Show 10",
    "Echo Show 15",
  ],

  // ── NINTENDO ───────────────────────────────────────────────────────────────
  Nintendo: [
    "Switch OLED",
    "Switch (modelo 2019)",
    "Switch Lite",
    "Switch (modelo original)",
    "3DS XL",
    "3DS",
    "2DS XL",
    "2DS",
    "New 3DS XL",
    "New 3DS",
    "DS Lite",
    "DSi XL",
    "DSi",
    "Game Boy Advance SP",
    "Game Boy Advance",
    "Game Boy Color",
    "Game Boy",
  ],

  // ── SONY (PlayStation) ─────────────────────────────────────────────────────
  // já coberto acima, mas adicionando consoles
  // ── CANON ──────────────────────────────────────────────────────────────────
  Canon: [
    "EOS R8",
    "EOS R50",
    "EOS R100",
    "EOS R6 Mark II",
    "EOS R5 C",
    "EOS R5",
    "EOS R3",
    "EOS R7",
    "EOS R10",
    "EOS 90D",
    "EOS 850D",
    "EOS 250D",
    "EOS M50 Mark II",
    "EOS M200",
    "PowerShot G7 X Mark III",
    "PowerShot G5 X Mark II",
    "PowerShot SX740 HS",
    "PIXMA G3160",
    "PIXMA G2160",
    "PIXMA G1160",
    "PIXMA MG3610",
    "PIXMA MX492",
    "PIXMA TS3110",
    "PIXMA TS5110",
    "PIXMA TS8310",
    "PIXMA G7010",
    "PIXMA G6010",
    "PIXMA G5010",
    "PIXMA G4010",
    "PIXMA G3010",
    "PIXMA G2010",
    "PIXMA G1010",
  ],

  // ── EPSON ──────────────────────────────────────────────────────────────────
  Epson: [
    "EcoTank L3250",
    "EcoTank L3150",
    "EcoTank L3110",
    "EcoTank L4260",
    "EcoTank L4160",
    "EcoTank L5290",
    "EcoTank L5190",
    "EcoTank L6270",
    "EcoTank L6190",
    "EcoTank L14150",
    "EcoTank L1800",
    "EcoTank L800",
    "WorkForce WF-2860",
    "WorkForce WF-3820",
    "WorkForce WF-7720",
    "Expression XP-4100",
    "Expression XP-2100",
    "Expression Photo XP-970",
    "SureColor SC-P700",
    "SureColor SC-P900",
    "FX-890II",
    "LQ-590II",
  ],

  // ── BROTHER ────────────────────────────────────────────────────────────────
  Brother: [
    "DCP-L2540DW",
    "DCP-L2520DW",
    "DCP-T220",
    "DCP-T420W",
    "DCP-T520W",
    "DCP-T720DW",
    "DCP-T820DW",
    "MFC-L2740DW",
    "MFC-L2720DW",
    "MFC-L3770CDW",
    "MFC-L3750CDW",
    "MFC-T920DW",
    "MFC-T4500DW",
    "HL-L2360DW",
    "HL-L2340DW",
    "HL-L3270CDW",
    "HL-L5200DW",
    "PT-D210",
    "PT-D600",
    "PT-E550W",
  ],

  // ── JBL ────────────────────────────────────────────────────────────────────
  JBL: [
    "Charge 5",
    "Charge 4",
    "Flip 6",
    "Flip 5",
    "Flip 4",
    "Clip 4",
    "Clip 3",
    "Go 3",
    "Go 2",
    "Xtreme 3",
    "Xtreme 2",
    "Boombox 3",
    "Boombox 2",
    "Pulse 5",
    "Pulse 4",
    "Partybox 310",
    "Partybox 110",
    "Partybox On-The-Go",
    "Tune 760NC",
    "Tune 720BT",
    "Tune 510BT",
    "Tune 230NC TWS",
    "Live Pro 2 TWS",
    "Live Free 2 TWS",
    "Vibe Beam",
    "Vibe 300TWS",
    "Reflect Flow Pro",
    "Reflect Mini NC",
    "Quantum 810",
    "Quantum 610",
    "Quantum 400",
    "Quantum 100",
  ],

  // ── INTELBRAS ──────────────────────────────────────────────────────────────
  Intelbras: [
    "Action RF 4.5",
    "Action RF 4.0",
    "Action A51",
    "Action A31",
    "Moto G Play (Intelbras)",
    "Roteador ACtion RG 1200",
    "Roteador ACtion RF 1200",
    "Roteador ACtion RF 900",
    "Roteador ACtion RG 1200",
    "Switch SF 800 Q+",
    "Switch SF 800",
    "Switch SG 800 Q+",
    "IP Camera VIP 1020",
    "IP Camera VIP 1220",
    "IP Camera VIP 3230",
    "DVR MHDX 1108",
    "DVR MHDX 1116",
    "NVR NVD 1108",
    "NVR NVD 1116",
    "Telefone IP TIP 125i",
    "Telefone IP TIP 200",
    "PABX I124",
    "PABX I200",
  ],

  // ── VAIO ───────────────────────────────────────────────────────────────────
  Vaio: [
    "FE14",
    "FE15",
    "FE14 VJFE41F11X",
    "FE15 VJFE52F11X",
    "FE14 i5",
    "FE15 i5",
    "FE14 i7",
    "FE15 i7",
    "SX14",
    "SX12",
    "Z",
    "Z Flip",
    "Pro PE",
    "Pro PG",
    "Pro PH",
    "Pro PJ",
    "Pro PK",
    "Pro PL",
    "Pro PM",
    "Pro PN",
    "Pro PO",
    "Pro PP",
  ],

  // ── AVELL ──────────────────────────────────────────────────────────────────
  Avell: [
    "A62 LIV",
    "A70 MOB",
    "B155 MAX",
    "C65 MOB",
    "G1513 MX",
    "G1513 FOX",
    "G1711 GTX",
    "G1711 RTX",
    "G1713 GTX",
    "G1713 RTX",
    "G1713 FOX",
    "Titanium B155",
    "Titanium B155 MAX",
    "Titanium A60",
    "Titanium A62",
    "Titanium A70",
    "Titanium C65",
  ],

  // ── COMPAQ ─────────────────────────────────────────────────────────────────
  Compaq: [
    "Presario CQ-27",
    "Presario CQ-29",
    "Presario CQ-23",
    "Presario CQ-25",
    "CQ27",
    "CQ29",
    "CQ23",
    "CQ25",
    "PRESARIO CQ-27",
    "PRESARIO CQ-29",
  ],

  // ── RAZER ──────────────────────────────────────────────────────────────────
  Razer: [
    "Blade 18",
    "Blade 16",
    "Blade 15",
    "Blade 14",
    "Blade Stealth 13",
    "Phone 2",
    "Phone",
    "Kiyo Pro",
    "Kiyo",
    "Seiren X",
    "Seiren Mini",
    "Seiren V2 Pro",
    "Seiren V2 X",
    "Barracuda X",
    "Barracuda Pro",
    "BlackShark V2 Pro",
    "BlackShark V2 X",
    "Kraken V3 Pro",
    "Kraken V3 X",
    "Nari Ultimate",
    "Nari Essential",
    "DeathAdder V3 Pro",
    "DeathAdder V3",
    "Viper V2 Pro",
    "Viper Mini",
    "Basilisk V3 Pro",
    "Basilisk V3",
    "Huntsman V2",
    "Huntsman Mini",
    "BlackWidow V4 Pro",
    "BlackWidow V3 Pro",
    "Ornata V3",
    "Cynosa V2",
    "Tartarus Pro",
    "Tartarus V2",
  ],

  // ── MSI ────────────────────────────────────────────────────────────────────
  MSI: [
    "Titan GT77",
    "Titan GT76",
    "Raider GE78 HX",
    "Raider GE77 HX",
    "Raider GE76",
    "Raider GE75",
    "Vector GP78 HX",
    "Vector GP77",
    "Vector GP76",
    "Stealth GS77",
    "Stealth GS76",
    "Stealth 16 Studio",
    "Stealth 15M",
    "Sword 17 HX",
    "Sword 16 HX",
    "Sword 15",
    "Katana GF76",
    "Katana GF66",
    "Katana 17",
    "Katana 15",
    "Pulse GL76",
    "Pulse GL66",
    "Pulse 17",
    "Pulse 15",
    "Crosshair 17",
    "Crosshair 15",
    "Creator Z17",
    "Creator Z16",
    "Creator M16",
    "Prestige 16 Studio",
    "Prestige 15",
    "Prestige 14",
    "Modern 15",
    "Modern 14",
    "Summit E16 Flip",
    "Summit E14 Flip",
  ],

  // ── TOSHIBA ────────────────────────────────────────────────────────────────
  Toshiba: [
    "Satellite C50",
    "Satellite C55",
    "Satellite C70",
    "Satellite L50",
    "Satellite L55",
    "Satellite P50",
    "Satellite P55",
    "Satellite S50",
    "Satellite S55",
    "Satellite S70",
    "Satellite S75",
    "Satellite U50",
    "Satellite U55",
    "Satellite Pro C50",
    "Satellite Pro L50",
    "Portégé Z30",
    "Portégé Z20t",
    "Tecra A50",
    "Tecra Z50",
    "Dynabook Satellite Pro",
    "Dynabook Tecra",
    "Dynabook Portégé",
  ],

  // ── GARMIN ─────────────────────────────────────────────────────────────────
  Garmin: [
    "Fenix 7X Sapphire Solar",
    "Fenix 7 Sapphire Solar",
    "Fenix 7S",
    "Fenix 6X Pro Solar",
    "Fenix 6 Pro Solar",
    "Fenix 6S Pro",
    "Forerunner 965",
    "Forerunner 955 Solar",
    "Forerunner 745",
    "Forerunner 645",
    "Forerunner 255",
    "Forerunner 55",
    "Forerunner 45",
    "Venu 3",
    "Venu 2 Plus",
    "Venu 2",
    "Venu Sq 2",
    "Vivoactive 5",
    "Vivoactive 4",
    "Vivoactive 4S",
    "Instinct 2X Solar",
    "Instinct 2 Solar",
    "Instinct 2",
    "Instinct Solar",
    "Instinct",
    "Lily 2",
    "Lily",
    "Vivomove Trend",
    "Vivomove Sport",
    "Vivomove 3",
    "Vivosmart 5",
    "Vivosmart 4",
    "Edge 1040 Solar",
    "Edge 840 Solar",
    "Edge 540 Solar",
    "Edge 540",
    "Edge 840",
    "Edge 1040",
    "Edge 530",
    "Edge 830",
    "Edge 1030 Plus",
  ],

  // ── AMAZFIT ────────────────────────────────────────────────────────────────
  Amazfit: [
    "GTR 4",
    "GTR 3 Pro",
    "GTR 3",
    "GTR 2e",
    "GTR 2",
    "GTR Mini",
    "GTS 4",
    "GTS 4 Mini",
    "GTS 3",
    "GTS 2e",
    "GTS 2",
    "GTS 2 Mini",
    "T-Rex Ultra",
    "T-Rex Pro",
    "T-Rex 2",
    "T-Rex",
    "Falcon",
    "Cheetah Pro",
    "Cheetah",
    "Balance",
    "Active",
    "Active Edge",
    "Band 7",
    "Band 5",
    "Bip 5",
    "Bip 5 Unity",
    "Bip 3 Pro",
    "Bip 3",
    "Bip U Pro",
    "Bip U",
    "Bip S",
    "Bip",
    "Verge Lite",
    "Verge",
    "Stratos 3",
    "Stratos+",
    "Stratos",
    "Pace",
  ],

  // ── FITBIT ─────────────────────────────────────────────────────────────────
  Fitbit: [
    "Charge 6",
    "Charge 5",
    "Charge 4",
    "Charge 3",
    "Inspire 3",
    "Inspire 2",
    "Inspire HR",
    "Inspire",
    "Luxe",
    "Sense 2",
    "Sense",
    "Versa 4",
    "Versa 3",
    "Versa 2",
    "Versa Lite",
    "Versa",
    "Ionic",
    "Blaze",
    "Surge",
    "Alta HR",
    "Alta",
    "Flex 2",
    "Flex",
    "Zip",
    "One",
    "Aria 2",
    "Aria Air",
  ],

  // ── GOPRO ──────────────────────────────────────────────────────────────────
  GoPro: [
    "HERO12 Black",
    "HERO11 Black Mini",
    "HERO11 Black",
    "HERO10 Black",
    "HERO9 Black",
    "HERO8 Black",
    "HERO7 Black",
    "HERO7 Silver",
    "HERO7 White",
    "HERO6 Black",
    "HERO5 Black",
    "HERO5 Session",
    "HERO4 Black",
    "HERO4 Silver",
    "HERO Session",
    "MAX",
    "Fusion",
  ],

  // ── DJI ────────────────────────────────────────────────────────────────────
  DJI: [
    "Mavic 3 Pro",
    "Mavic 3 Classic",
    "Mavic 3",
    "Mavic 3 Cine",
    "Mavic Air 2S",
    "Mavic Air 2",
    "Mavic Mini 3 Pro",
    "Mavic Mini 3",
    "Mavic Mini 2 SE",
    "Mavic Mini 2",
    "Mavic Mini",
    "Mini 4 Pro",
    "Mini 3 Pro",
    "Mini 3",
    "Mini 2 SE",
    "Mini 2",
    "Mini SE",
    "Mini",
    "Air 3",
    "Air 2S",
    "Phantom 4 Pro V2.0",
    "Phantom 4 Pro",
    "Phantom 4",
    "Inspire 3",
    "Inspire 2",
    "FPV",
    "Avata 2",
    "Avata",
    "Osmo Mobile 6",
    "Osmo Mobile SE",
    "Osmo Mobile 5",
    "Osmo Pocket 3",
    "Osmo Pocket 2",
    "Osmo Pocket",
    "Osmo Action 4",
    "Osmo Action 3",
    "Osmo Action",
    "RS 3 Pro",
    "RS 3",
    "RS 3 Mini",
    "RS 2",
    "RSC 2",
  ],

  // ── NIKON ──────────────────────────────────────────────────────────────────
  Nikon: [
    "Z9",
    "Z8",
    "Z7 II",
    "Z6 III",
    "Z6 II",
    "Z5 II",
    "Z5",
    "Z50",
    "Zfc",
    "Z30",
    "D850",
    "D780",
    "D7500",
    "D5600",
    "D3500",
    "D3400",
    "D3200",
    "D3100",
    "COOLPIX P1000",
    "COOLPIX P950",
    "COOLPIX B600",
    "COOLPIX B500",
    "COOLPIX A1000",
    "COOLPIX A900",
  ],

  // ── FUJIFILM ───────────────────────────────────────────────────────────────
  Fujifilm: [
    "X-T5",
    "X-T4",
    "X-T3",
    "X-T30 II",
    "X-T30",
    "X-T20",
    "X-T10",
    "X-S20",
    "X-S10",
    "X-Pro3",
    "X-Pro2",
    "X-H2S",
    "X-H2",
    "X-H1",
    "X-E4",
    "X-E3",
    "X100VI",
    "X100V",
    "X100F",
    "GFX100S",
    "GFX100",
    "GFX50S II",
    "GFX50S",
    "Instax Mini 12",
    "Instax Mini 11",
    "Instax Mini 9",
    "Instax Mini 40",
    "Instax Mini 70",
    "Instax Mini 90",
    "Instax Square SQ6",
    "Instax Wide 300",
    "Instax Link Wide",
    "Instax Mini Link 2",
    "Instax Mini Link",
  ],

  // ── PANASONIC ──────────────────────────────────────────────────────────────
  Panasonic: [
    "Lumix S5 II",
    "Lumix S5",
    "Lumix S1R",
    "Lumix S1",
    "Lumix G9 II",
    "Lumix G9",
    "Lumix GH6",
    "Lumix GH5 II",
    "Lumix GH5",
    "Lumix G100",
    "Lumix G95",
    "Lumix G85",
    "Lumix FZ300",
    "Lumix FZ80",
    "Lumix ZS200",
    "Lumix ZS80",
    "Lumix ZS70",
    "Lumix ZS60",
    "Lumix LX100 II",
    "Lumix LX100",
    "Lumix TZ200",
    "Lumix TZ100",
    "Lumix TZ90",
    "Lumix TZ80",
    "Lumix TZ70",
  ],

  // ── BOSE ───────────────────────────────────────────────────────────────────
  Bose: [
    "QuietComfort Ultra Headphones",
    "QuietComfort Ultra Earbuds",
    "QuietComfort 45",
    "QuietComfort 35 II",
    "QuietComfort 35",
    "QuietComfort 25",
    "QuietComfort 20",
    "QuietComfort Earbuds II",
    "QuietComfort Earbuds",
    "Sport Earbuds",
    "Sport Open Earbuds",
    "SoundSport Free",
    "SoundSport",
    "SoundLink Flex",
    "SoundLink Revolve+",
    "SoundLink Revolve",
    "SoundLink Mini II",
    "SoundLink Mini",
    "SoundLink Color II",
    "SoundLink Color",
    "SoundLink Micro",
    "SoundLink Around-Ear II",
    "SoundLink On-Ear",
    "700 Headphones",
    "Frames Tempo",
    "Frames Rondo",
    "Frames Alto",
    "Home Speaker 500",
    "Home Speaker 300",
    "Portable Smart Speaker",
    "Smart Soundbar 900",
    "Smart Soundbar 600",
    "Smart Soundbar 300",
    "TV Speaker",
    "Lifestyle 650",
    "Lifestyle 600",
  ],

  // ── SENNHEISER ─────────────────────────────────────────────────────────────
  Sennheiser: [
    "Momentum 4 Wireless",
    "Momentum 3 Wireless",
    "Momentum 2 Wireless",
    "Momentum True Wireless 3",
    "Momentum True Wireless 2",
    "Momentum True Wireless",
    "HD 660S2",
    "HD 660S",
    "HD 650",
    "HD 600",
    "HD 560S",
    "HD 450BT",
    "HD 350BT",
    "HD 250BT",
    "PXC 550-II",
    "PXC 480",
    "CX Plus True Wireless",
    "CX True Wireless",
    "CX 400BT",
    "CX 300S",
    "CX 150BT",
    "IE 900",
    "IE 600",
    "IE 300",
    "IE 200",
    "IE 100 Pro",
    "IE 40 Pro",
    "EW-D",
    "EW 100 G4",
    "EW 300 G4",
    "EW 500 G4",
    "MKH 416",
    "MKH 50",
    "MK 4",
    "MK 8",
    "e 835",
    "e 945",
    "e 965",
  ],

  // ── BEATS ──────────────────────────────────────────────────────────────────
  Beats: [
    "Studio Pro",
    "Studio3 Wireless",
    "Studio Buds+",
    "Studio Buds",
    "Fit Pro",
    "Powerbeats Pro",
    "Powerbeats 3",
    "Beats Flex",
    "Solo4",
    "Solo3 Wireless",
    "Solo Pro",
    "EP",
    "Pill+",
    "Pill 3.0",
  ],

  // ── EDIFIER ────────────────────────────────────────────────────────────────
  Edifier: [
    "W820NB Plus",
    "W820NB",
    "W830BT",
    "W800BT Plus",
    "W800BT",
    "W600BT",
    "W330NB",
    "W240TN",
    "W200T Mini",
    "W200BT SE",
    "W200BT",
    "W100BT",
    "TWS330NB",
    "TWS330",
    "TWS200",
    "TWS1 Pro 2",
    "TWS1 Pro",
    "TWS1",
    "NeoBuds Pro 2",
    "NeoBuds Pro",
    "NeoBuds S",
    "R1280T",
    "R1280DB",
    "R1700BT",
    "R1700BTs",
    "R2000DB",
    "S3000 Pro",
    "S2000 MKIII",
    "S1000DB",
    "S350DB",
    "S330DB",
    "D32",
    "D12",
    "MR4",
    "MR3",
  ],

  // ── LOGITECH ───────────────────────────────────────────────────────────────
  Logitech: [
    "MX Master 3S",
    "MX Master 3",
    "MX Master 2S",
    "MX Anywhere 3S",
    "MX Anywhere 3",
    "MX Keys S",
    "MX Keys",
    "MX Keys Mini",
    "MX Mechanical Mini",
    "MX Mechanical",
    "G502 X Plus",
    "G502 X",
    "G502 Hero",
    "G502 Lightspeed",
    "G Pro X Superlight 2",
    "G Pro X Superlight",
    "G Pro Wireless",
    "G Pro X",
    "G Pro",
    "G403 Hero",
    "G305",
    "G304",
    "G203",
    "G102",
    "G915 TKL",
    "G915",
    "G815",
    "G713",
    "G512",
    "G413",
    "G213",
    "G733",
    "G535",
    "G432",
    "G335",
    "G332",
    "G231",
    "G435",
    "G560",
    "G560 LIGHTSYNC",
    "G933s",
    "G733 Lightspeed",
    "C922 Pro",
    "C920",
    "C920s",
    "C310",
    "C270",
    "StreamCam",
    "Brio 4K",
    "Brio 500",
    "Brio 100",
    "K380",
    "K480",
    "K780",
    "K860",
    "Pebble Keys 2 K380s",
    "Pebble M350s",
    "M350",
    "M330",
    "M220",
    "M185",
    "M170",
  ],

  // ── TP-LINK ────────────────────────────────────────────────────────────────
  "TP-Link": [
    "Archer AX73",
    "Archer AX55",
    "Archer AX50",
    "Archer AX23",
    "Archer AX20",
    "Archer AX10",
    "Archer C6",
    "Archer C5400X",
    "Archer C3200",
    "Archer C1200",
    "Archer C900",
    "Archer C80",
    "Archer C60",
    "Archer C50",
    "Archer C20",
    "TL-WR940N",
    "TL-WR941ND",
    "TL-WR841N",
    "TL-WR840N",
    "TL-WR820N",
    "TL-WR810N",
    "TL-WR800N",
    "Deco X68",
    "Deco X60",
    "Deco X50",
    "Deco X20",
    "Deco M9 Plus",
    "Deco M5",
    "Deco M4",
    "RE700X",
    "RE600X",
    "RE500X",
    "RE450",
    "RE305",
    "RE200",
    "TL-SG108",
    "TL-SG116",
    "TL-SG1024D",
    "TL-SF1008D",
  ],

  // ── D-LINK ─────────────────────────────────────────────────────────────────
  "D-Link": [
    "DIR-X5460",
    "DIR-X3260",
    "DIR-X1560",
    "DIR-X1860",
    "DIR-3060",
    "DIR-2660",
    "DIR-1960",
    "DIR-1360",
    "DIR-882",
    "DIR-878",
    "DIR-842",
    "DIR-819",
    "DIR-815",
    "DIR-809",
    "DIR-806",
    "DIR-805",
    "DIR-803",
    "DIR-802",
    "DIR-615",
    "DIR-610",
    "DWR-978",
    "DWR-956",
    "DWR-932",
    "DWR-921",
    "DWR-910",
    "DGS-1008P",
    "DGS-1016D",
    "DGS-1024D",
    "DES-1008D",
    "DES-1016D",
  ],
};

/**
 * Retorna a lista de modelos para uma marca específica.
 * Se a marca não tiver modelos cadastrados, retorna array vazio.
 */
export function getModelsForBrand(brand: string): string[] {
  if (!brand) return [];
  // Busca exata primeiro
  if (BRAND_MODELS[brand]) return BRAND_MODELS[brand];
  // Busca case-insensitive como fallback
  const key = Object.keys(BRAND_MODELS).find(
    (k) => k.toLowerCase() === brand.toLowerCase()
  );
  return key ? BRAND_MODELS[key] : [];
}

/** Lista de todas as marcas disponíveis (chaves do BRAND_MODELS, ordenadas) */
export const BRAND_LIST: string[] = Object.keys(BRAND_MODELS).sort();
